spring.application.name=healthcare
server.port=8080

spring.ai.chat.client.enabled=false
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.organization-id=${OPENAI_ORG_KEY}
spring.ai.openai.project-id=${OPENAI_PROJECT_ID}
spring.ai.openai.chat.option.model=gpt-4o-mini
openai.api.url=https://api.openai.com/v1/chat/completions

spring.ai.vertex.ai.gemini.project-id=gen-lang-client-0909072327
spring.ai.vertex.ai.gemini.location=us-central1
spring.ai.vertex.chat.option.model=gemini-1.5-flash


