server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

app:
  upload:
    dir: "C:/Users/Admin/Downloads/ingest_data" # Configurable path for local testing

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  application:
    name: document-processor
  kafka:
    consumer:
      group-id: document-processor-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
