server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

app:
  upload:
    dir: "C:/Users/Admin/Downloads/ingest_data" # Configurable path for local testing

management:
  tracing:
    sampling:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  application:
    name: retrieval-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:postgresql://localhost:5432/vectordb
    username: user
    password: password
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        initialize-schema: true
  
openai:
  video:
    model: text-to-video-model
    duration: 5
    poll-attempts: 20
    poll-delay-ms: 2000
gemini:
  video:
    project-id: ${GEMINI_PROJECT_ID:healthcare-agent-project}
    location: us-central1
    model: "imagen-3.0-generate-001" # Check availability or use appropriate model
    poll-attempts: 20
    poll-delay-ms: 5000
  chat:
    enabled: false
